name: External PR Branch Enforcer

on:
  pull_request_target:
    types: [opened, edited, synchronize]

jobs:
  check-target-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR target branch
        if: github.event.pull_request.base.ref != 'develop' && (github.event.pull_request.author_association != 'OWNER' && github.event.pull_request.author_association != 'MEMBER')
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            
            // Post comment on PR
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.name,
              issue_number: pr.number,
              body: '🤖 Attention! Always use the develop branch for your PRs instead of ' + pr.base.ref + '.' 
            });
            
            // Change base branch to develop
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.name,
              pull_number: pr.number,
              base: 'develop'
            });
            
            // Add comment about the automatic change
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.name,
              issue_number: pr.number,
              body: '🤖 I\'ve automatically updated this PR to target the develop branch.'
            });