name: Lint & Format Check

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-and-format:
    name: Run Linters & Formatters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Java environment (for Checkstyle & ktlint)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      # Set up Node.js (for Prettier & ESLint)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install Prettier and ESLint if package.json exists
      - name: Install Prettier & ESLint
        run: |
          if [ -f "package.json" ]; then
            npm install --save-dev prettier eslint
          fi

      # Run Prettier to check formatting
      - name: Run Prettier
        run: |
          if [ -f "package.json" ]; then
            npx prettier --check "**/*.{js,ts,json,md,yml}"
          else
            echo "Skipping Prettier - No JavaScript/TypeScript files found."
          fi

      # Run ESLint for JavaScript/TypeScript files
      - name: Run ESLint
        run: |
          if [ -f "package.json" ]; then
            npx eslint "**/*.{js,ts}" --max-warnings=0
          else
            echo "Skipping ESLint - No JavaScript/TypeScript files found."
          fi

      # Run Checkstyle for Java linting
      - name: Run Checkstyle
        run: mvn checkstyle:check

      # Run ktlint for Kotlin linting (if applicable)
      - name: Run ktlint
        run: |
          if [ -f "gradlew" ]; then
            chmod +x gradlew
            ./gradlew ktlintCheck
          else
            echo "Skipping ktlint - No Kotlin project detected."
          fi